### PR TITLE
Vv/#87 invoices updates

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Change invoices pagination to query by year instead of `Limit` setting
- Sort yearly data by date
- Display next payment attempt field
- Add copy button for Invoice ID and Charge ID fields
- Show amount currency
- Show invoices status as chip component
- Create invoice page with download button

### CODE REVIEW

**Comment by acidbiscuit** [comment]
@davidgatti I'm not sure what was meant:

> Display data in the local user country setting, like time format, money etc. 

We currently show time in user timezone. If there is anything else should be changed, please add details.

**Comment by davidgatti** [comment]
> We currently show time in user timezone. If there is anything else should be changed, please add details.

All good then.

**Review by davidgatti — COMMENTED** [review]
Copying is not working.

Screen Shot 2021-01-24 at 8 09 10 PM

**Comment by acidbiscuit** [comment]
@davidgatti I've added a fix for invoice page open when click copy, but I wasn't able to reproduce the error mentioned above. Please, give it a try to check if issue persists.

**Review by davidgatti — APPROVED** [review]

**Pull request merged**
