### PR TITLE
feat: #136 payment add pre-filled country and postal code

### LINKED ISSUE #136: Add 2 new fields in payment
Ad a drop down of countries, and is possible mark the user country based on the time zone of the browser. And an input for the zip code. If possible with real validation based on the selected country, more about the formatting, and not if it is really valid. 

And for this, please don't use any Google stuff ;)

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Add fetching ip info with https://ip-api.com/ service
- Add countries JSON in static data with async fetcning to leverage cache to the browser and do not include the list in the bundle
- Populate stripe widget with postal code and payment form with country from user ip info

Closes #136

### CODE REVIEW

**Comment by davidgatti** [comment]
@acidbiscuit what are you using the https://ip-api.com/ service for?

**Comment by acidbiscuit** [comment]
@davidgatti We use it to get user country and postal code.

**Comment by davidgatti** [comment]
This is not need, the Postal will be typed, and when it comes to the country, please use the user time zone, to set the default country.

**Comment by acidbiscuit** [comment]
@davidgatti There is no reliable way to get user country from system timezone in the browser. IP details is the most common way to assume user's country.

**Comment by davidgatti** [comment]
Why do you say that? `Intl.DateTimeFormat().resolvedOptions().timeZone` seams to be pretty reliable. No?

**Comment by acidbiscuit** [comment]
@davidgatti `Intl.DateTimeFormat().resolvedOptions().timeZone` provides a timezone, not a country & postal code. Since we agree to skip postal code, another option is available for us to get user's country. I've added timezones list for each country in static JSON to lookup matching county from user system timezone. IP info lookup has been removed.

Please, take a look.

**Comment by davidgatti** [comment]
Perfect.

**Pull request merged**
