### PR TITLE
feat: #190 redesign subscription page

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Update layout of new subscription page
- Update layout of existing subscription page

Note: this issue is not finalized due to missing requests and information. More in the issue. Looking forward for you feedback.

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
Screen Shot 2021-02-21 at 7 39 27 PM

**Comment by davidgatti** [comment]
I forgot to mention this, now when the user submits the payment you need to add a new entry in the DB for the seelcted price, this is the payload for DDB:

```
{
    "pk": "us-east-1:93c39d6c-954e-469c-99f6-aafb2ab28de2",
    "sk": "user#stripe#subscription#price",
    "price_id": "price_1IAMmEG1wg42NuVobjAGJ7gx"
}
```

And this are the price IDs

```
year=price_1IAvr4G1wg42NuVoNcVUMMV7
month=price_1IAMmEG1wg42NuVobjAGJ7gx
```

**Comment by acidbiscuit** [comment]
@davidgatti I though formula should be displayed only when coupon is applied.

What kind of formula should we show for monthly subscription?

**Comment by acidbiscuit** [comment]
@davidgatti  By the way, I can't remember if a ever saw a formula when subscribing to a service. Common representation of a discount is "original" price crossed and "new" lower price aside of it. Maybe we can use such approach as well?

**Comment by davidgatti** [comment]
@acidbiscuit I am not everybody ;) and someone that really dose not care about what other people think about me or my crazy ideas :) I like to experiments with different thoughts, and approaches to life. And so I want to make the payment page clear and fun. 

I want the equation to make it clear how the calculation is done.

# Monthly payment - no coupon

($1 * 12) - 0% = $12

# Monthly payment - with coupon

($1 * 12) - n% = $result

# yearly payment - with coupon

$10 - n% = $result

# yearly payment - no coupon

$10 - 0% = $10

:)

**Comment by acidbiscuit** [comment]
@davidgatti 

Please, check updated version:
- Formula is displayed as per description
- Improved layout
- Added stripe widget text
- Added request in `money` table with selected price_id

**Comment by davidgatti** [comment]
@acidbiscuit is it me or you are not passing the payload of 

```
{
    "cupon_id": "g5mSqxS5"
}
```

to the cupon validation lambda?

**Comment by davidgatti** [comment]
- swap positoin
- make $ part bigger font.

Screen Shot 2021-02-24 at 4 01 16 PM

**Comment by davidgatti** [comment]
When you click on the delete subscription, you are deleting the wrong thing, you have to delete this entry from the DDB: `user#stripe#subscription#details`

**Comment by acidbiscuit** [comment]
@davidgatti To confirm, in order to check if user has subscription we should fetch `user#stripe#subscription#price` and in order to cancel subscription we should delete `user#stripe#subscription#details`, right?

**Comment by davidgatti** [comment]
- checking of a subscription will be done through a lambda that you will have to invoke, that I need to make
- And yes, when you delete the DDB entry with the `pk` of the user and the `sk` of `user#stripe#subscription#details` this will trigger an event that will delete the subscription from Stripe itself. While the price can stay as it is, since whe nthe user will chose the price again, either it will be updated or stay the same.

**Comment by davidgatti** [comment]
- checking of a subscription will be done through a lambda that you will have to invoke, that I need to make
- And yes, when you delete the DDB entry with the `pk` of the user and the `sk` of `user#stripe#subscription#details` this will trigger an event that will delete the subscription from Stripe itself. While the price can stay as it is, since whe nthe user will chose the price again, either it will be updated or stay the same.

**Comment by davidgatti** [comment]
Add button to change the pricing plan, when clicked you switch to the oposite plan, with a modal for confirmation, and what you do in the background you do a DDB put query with the new price ID.

Screen Shot 2021-02-25 at 12 49 01 PM

**Comment by davidgatti** [comment]
Allow change of price

Screen Shot 2021-02-26 at 10 11 31 AM

Remove this button

Screen Shot 2021-02-26 at 10 26 54 AM

**Comment by acidbiscuit** [comment]
@davidgatti I've made following changes:

- Remove "Remove all" button on subscription details page
- Add dropdown for subscription plan switch
- Add plan switch confirmation modal
- Update `user#stripe#subscription#price` field in DDB on subscription cancel or plan change
- Add plan selection after subscription is cancelled

Note: we are currently missing a way to find if user is actually subscribed. Even though I am deleting `user#stripe#subscription#details` on subscription cancel, there is no place in code where we create or query `user#stripe#subscription#details`. I need your input on correct way to determine if user has active subscription.

**Comment by davidgatti** [comment]
@acidbiscuit the pR that you reviewd, did you see that I did remove `user#` from all the `sk`? there is no more user prepended to the `sk` string, so from `user#stripe#subscription#details` to `stripe#subscription#details`

This means any put, get etc can't have `user#` in the beginngin.

**Comment by acidbiscuit** [comment]
@davidgatti Noted. 

Still though, do we create `stripe#subscription#details` from the front-end?

**Comment by davidgatti** [comment]
No, I dod that in the back-end when the price gets saved in the DDB.

**Comment by acidbiscuit** [comment]
@davidgatti I've added a proper way to manage subscription and payment method. Please, give it a try.

**Pull request merged**
