### PR TITLE
feat: #214 add profile interface page

### LINKED ISSUE #214: Add new profile menu called UI
- after the personal info add a UI tab
- Add on the page an option to switch the UI theme from dark to light, and save the setting in cognito which will overwrite the OS setting if present.
- After that add a slider to be able to change the font size on the site. From normal to bigger options. And save the setting to cognito, and load it when the user visits the page

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Add profile interface page
- Add Color Preference setting and store it in CognitoSync
- Set application theme from user color preference setting

Closes #214

### CODE REVIEW

**Review by davidgatti — COMMENTED** [review]
Question, would it better to remove the entry when setting system settings?

**Comment by acidbiscuit** [comment]
@davidgatti We can do that with some additional logic on the front-end. I'll update the request.

**Comment by davidgatti** [comment]
That be ideal. Since the default state for each new user is system setting, which is no value at all in Cognito.

**Comment by acidbiscuit** [comment]
@davidgatti Done. Though, it appears that `remove` operation keeps dataset key entry with `null` value.

**Comment by davidgatti** [comment]
@acidbiscuit this is a new part of AWS that I also never worked with so I'm learning along. Attached bellow is a screenshot of what is the result. I have some questions:

- So it seams that deleting a Key won't remove it from the DB, but just mark it as deleted
- if this is the case then maybe we should roll back to the previous approach?
- from your perspective what would the the most straight forward approach?

Screen Shot 2021-03-11 at 8 40 15 AM

**Comment by acidbiscuit** [comment]
@davidgatti I don't think there is a benefit of rolling back to previous options. Hypothetically, the only benefit would be that in case you need to set the value for some users manually, you would simply delete it from Cognito, rather then type "system" in value field. Let's keep it as it is.

**Pull request merged**
