### PR TITLE
feat: #163 update email in db after change

### LINKED ISSUE #163: Update the user email in DDB
When a user chagnes the email in their profile, you also have to update the DDB entry with the SK `user#basic`. Bellow is the structure of the record:

```
{
  "email": "pm@abiscuit.io",
  "pk": "us-east-1:e98a991d-dd46-4b1a-9255-4cdb0c89ff5c",
  "sk": "user#basic",
  "sub": "625305b0-df6d-4940-a631-fc784385f11f"
}
```

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Add user record update after successful email verification in email verification modal
- Add user record update on log in, in case authenticated user email does not match existing user record

Closes #163

### CODE REVIEW

**Comment by davidgatti** [comment]
From the code I can't figure when do you change it. Do you change it when the user hit submit, or when it confirms?

**Comment by acidbiscuit** [comment]
@davidgatti We update the record in 2 cases:

1) After successful confirmation in email verification modal
2) During sign in, in case DDB record and current authenticated Amplify user emails do not match.

**Comment by davidgatti** [comment]
So, I'd like to change I think this behavior to chagne it when the user hit save, because when that happens, the email will be chagned also in Cognito n the state unconfirmed. But regardless of the state it is replaced. then if the user would like to clcik cance, ale re-chagne it, that is OK, since we save the email at the click of the button, all will match. 

So we have one place to do the chagne.

**Comment by acidbiscuit** [comment]
@davidgatti Your solution seems to be working as well. Please, check the update.

**Review by davidgatti — APPROVED** [review]

**Pull request merged**
