### PR TITLE
feat: #47 add app loader snackbar

### LINKED ISSUE #47: Add loading spinners
Is it possible to have a notification showing up every time we wait for something to load? Like the stripe widget, or any other network activity?

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Add app loader snackbar and apply for content and form loading

Closes #47

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
Now we have 2 spinners, we have to decide on one, I'd like to have the one that is in the middle of the page, and spins with a text bellow that sayis `loading`, so it is in the user face and it is clear.

Also the spinner needs to be every time content is loaded, for example when you wait for the avatar, there is not spinner.

Screen Shot 2021-01-05 at 10 04 28 PM

**Comment by acidbiscuit** [comment]
@davidgatti

We can have spinners in-place where content is expected or interaction has happened:

1) Page content fetching (e.g. payment details loading). Just need to add "Loading" word.
2) Form submission loading state in submit buttons (e.g. profile update, address update, email verification). This loader also disables multiple time form submission.
3) Instead of an avatar, until it is loaded.

What is the purpose of a snackbar loader in such case? Should be remove it?

**Comment by davidgatti** [comment]
@acidbiscuit so as we discussed on the phone, lets keep it this way where each page has the correct loading screen based on the type of content. 

One thing I'd like to improve, for the spinner, that is for the hole content, add it to the center, and write `loading` bellow the spinner.

**Comment by acidbiscuit** [comment]
@davidgatti Please, check updated version

- App loader snackbar removed
- Add ProgressContent component to use as content loader and apply on Payments page

**Pull request merged**
